---
- name: "download nodeJS"
  become: true
  shell: |
    sudo apt-get update -y
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - 

- name: "install node"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install n"
  npm:
    name: n
    global: yes

- name: "change to node 13.8.0"
  become: true
  shell: |
    sudo n 13.8.0

- name: "Install PM2"
  npm:
    name: pm2
    global: yes