---
- name: "download nodeJS"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - 
    sudo apt-get install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0

- name: "Install PM2"
  npm:
    name: pm2
    global: yes